application: itsgoinguplite
version: 1-10
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static


- url: /favicon.ico
  static_files: static/media/img/favicon.ico
  upload: static/media/img/favicon.ico

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /.*
  script: index.py
  secure: always
  
